version: "3.7"
services:
  pigallery:
    container_name: pigallery
    image: bpatrik/pigallery2:latest
    command: sh -c 'bin/wait-for mariadb:3306 -- --Server-Database-mysql-host=pigallery --Server-Database-mysql-username=root --Server-Database-mysql-password=is04aac! --Server-Database-mysql-database=pigallery'
    restart: always
    networks:
      - traefik_proxy
      - mariadb
    ports:
      - "9876:80"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /media/usb/config/pigallery:/app/data/config
      - /media/usb/config/mariadb/data:/app/data/db
      - /media/usb/config/pigallery/tmp:/app/data/tmp
      - /media/usb/Windows:/app/data/images
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      ## HTTP Routers
      - "traefik.http.routers.pigallery-rtr.entrypoints=https"
      - "traefik.http.routers.pigallery-rtr.rule=HostHeader(`pigallery.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.pigallery-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.pigallery-rtr.service=pigallery-svc"
      - "traefik.http.services.pigallery-svc.loadbalancer.server.port=80"
networks:
  traefik_proxy:
    external: true
  mariadb:
    external: true
